ReithanKurau/SelfShelf

app/views/pages/home.html.erb

testing to see if files updates

shouldn't have changed much, testing git

---

app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss

Fonts added for the official app

Fonts added

---

db/seeds.rb

Add20seeds

---

app/assets/stylesheets/components/_book.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/interests/show.html.erb
app/views/shelf_interests/show.html.erb

Still showpages

---

app/controllers/comments_controller.rb
app/controllers/interests_controller.rb
app/controllers/shelf_interests_controller.rb
app/models/interest.rb
app/models/shelf_interest.rb
app/models/user.rb
app/views/shelf_interests/show.html.erb
config/routes.rb

User opinion about the book is added. The User is the only one capable to comment in their own shelf-interest.

User shelf-review is done

---

app/views/interests/index.html.erb

added search

---

app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_shelf.scss
app/controllers/pages_controller.rb
app/controllers/users_controller.rb
app/models/interest.rb
app/views/interests/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_nav_bottom.html.erb
app/views/shelf_interests/index.html.erb
app/views/users/edit.html.erb
app/views/users/show.html.erb
db/seeds.rb

No more problems

---

app/views/interests/show.html.erb
app/views/pages/home.html.erb

The plus was checked

---

db/seeds.rb

added genres to movies to fix create

added genres

---

app/controllers/interests_controller.rb
app/models/interest.rb
app/models/shelf_interest.rb
app/views/interests/index.html.erb
app/views/interests/show.html.erb
db/migrate/20241130092302_add_details_to_shelf_interests.rb
db/schema.rb
db/seeds.rb

added columns to shelf interests and made api search for movies

fixing models

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_tabs.scss
app/controllers/invitations_controller.rb
app/controllers/users_controller.rb
app/models/invitation.rb
app/models/shelf_interest.rb
app/models/user.rb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20241201050244_create_invitations.rb
db/schema.rb
test/controllers/friendships_controller_test.rb
test/controllers/invitations_controller_test.rb
test/models/invitation_test.rb

Addingfriends

---

app/controllers/invitations_controller.rb

fixed typo

---

app/views/users/show.html.erb

tabs work but dont look good

---

app/controllers/shelf_interests_controller.rb
app/views/shelf_interests/index.html.erb
app/views/shelf_interests/shelf_filtered.html.erb

you can see other shelves properly

added names to shelves

---

app/assets/stylesheets/components/_shelf.scss
db/seeds.rb

fixed default

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_shelf.scss
app/controllers/shelf_interests_controller.rb
app/models/favorite.rb
app/models/interest.rb
app/models/user.rb
app/views/shelf_interests/index.html.erb
app/views/shelf_interests/shelf_filtered.html.erb
app/views/shelf_interests/show.html.erb
app/views/users/show.html.erb
config/initializers/acts_as_favoritor.rb
config/routes.rb
db/migrate/20241204023838_acts_as_favoritor_migration.rb
db/schema.rb
db/seeds.rb

divides filtered into favorites and not
you can favorite items in your library

Filteredindex

---

app/assets/config/manifest.json.erb

hopefully this works

---

app/views/users/show.html.erb

friends tab looks a little better

friends page in tabs but looks odd

---

app/views/shelf_interests/index.html.erb

Changed it to "Your room" if you are the user

changed name if your shelf

---

app/assets/stylesheets/components/_card_item.scss
app/controllers/shelf_interests_controller.rb
app/views/shelf_interests/_shelf_filtered_card.html.erb
app/views/shelf_interests/shelf_filtered.html.erb
app/views/shelf_interests/show.html.erb
app/views/users/show.html.erb
config/routes.rb

added back and favorite buttons

added back buttons and favorite buttons

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_shelf.scss
app/controllers/shelf_interests_controller.rb
app/views/shelf_interests/index.html.erb
app/views/shelf_interests/shelf_filtered.html.erb

fav corrected

---

app/controllers/shelf_interests_controller.rb

fav routes to the filtered shelf
